version: 2

jobs:
  macos:
    macos:
      xcode: "11.0.0"
    steps:
      - checkout
      - run: HOMEBREW_NO_AUTO_UPDATE=1 brew install openssl@1.1
      - run: swift build
      - run: swift test
  macos-release:
    macos:
      xcode: "11.0.0"
    steps:
      - checkout
      - run: HOMEBREW_NO_AUTO_UPDATE=1 brew install openssl@1.1
      - run: swift build -c release
  bionic:
    docker:
      - image: vapor/swift:5.1-bionic
    steps:
      - checkout
      - run: apt-get update; apt-get install -y libssl-dev zlib1g-dev
      - run: swift build
      - run: swift test
  bionic-release:
    docker:
      - image: vapor/swift:5.1-bionic
    steps:
      - checkout
      - run: apt-get update; apt-get install -y libssl-dev zlib1g-dev
      - run: swift build -c release

workflows:
  version: 2
  tests:
    jobs:
      # - macos
      # - macos-release
      - bionic
      - bionic-release
